<template>
<q-page-container>
  <q-tabs align="center">
         <a href="#a6"><q-route-tab to="#a6" label="Page One" /></a>
        <q-route-tab to="#a4" label="Page Two" />
        <router-link to="#a5" label="Page Two" >page 5 </router-link>
        <q-route-tab to="#a6" label="Page 6" />
        <div to="#a6" clicable> div 6 </div>
  </q-tabs>

    <div id="a1">1Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
 <br/>
  <div id="a2">2Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
  <br/>
  <div id="a3">3Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
 <br/>
   <div id="a4">4Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
<br/>
  <div id="a5">5Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
<br/>
  <div id="a6">6Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi placeat nostrum delectus labore expedita, quidem laborum voluptatibus fugiat in modi dolorum cumque, esse neque quasi quam illum vero animi incidunt, voluptates rem unde est dolorem? Eveniet aliquam animi, dolorum fuga vel nostrum vitae itaque molestiae eos distinctio omnis asperiores cum dolor ipsum modi quos voluptatum obcaecati quam dolore dolorem. Doloremque eum eius quam dolor accusantium quo corrupti qui magnam architecto error. Soluta nesciunt aspernatur ipsam doloribus, maxime esse quae dignissimos accusantium velit sint culpa assumenda magni ullam labore nihil molestiae, sed delectus pariatur? Voluptate, quis! Quaerat animi illo odit architecto modi eaque delectus, aliquam quam corporis, veniam reiciendis eum quasi non sit excepturi harum? Nulla unde quod excepturi est, deserunt vitae commodi cumque placeat quam earum non dicta. Repellat recusandae exercitationem, maiores modi tempore perferendis amet quae, a consequatur impedit necessitatibus molestias fugit inventore quos totam, ex quo! Ex ipsum mollitia eveniet animi itaque nemo assumenda quisquam rem reiciendis. Minus beatae est totam hic molestiae suscipit unde eum quo inventore nisi voluptas modi, corrupti in facere. Ea doloremque, reprehenderit dolor consequuntur vel tempore magni adipisci? Veritatis deserunt, dolorem quam repudiandae ipsum possimus tempore, aliquid libero soluta quisquam minima reiciendis iusto.</div>
<br/>
</q-page-container>
</template>

<script>
export default {
  name: 'PageIndex'
}
</script>
